# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Race' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Race
pod 'RealmSwift'
 pod 'Firebase'
 pod 'FirebaseCore'
 pod 'FirebaseMessaging'
 pod 'FirebaseCrashlytics'

end
